id: D0057A967
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-13T03:40:14+00:00'
last_modified: '2022-05-30T04:42:03.697444+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    26bf:
      image_group_id: I1PD95942
      title: གཏན་ཚིགས་ཀྱི་ཐིགས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1198
      order: 97
      base_file: 26bf.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
