id: 39060ef708d84fc3a1de12eafb80e781
initial_creation_type: ocr
source_metadata:
  volumes:
    dcd29bdec5ce482b97e6d6cdee25af65:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ''
      total_pages: 1198
      volume_number: 97
